spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/music?characterEncoding=UTF-8
    username: root
    password: joonyoung58#
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9443